### ISSUE TITLE
编辑会报错，只能删除后添加

### ISSUE THREAD

**Issue by ghostry** [0xJacky/cdn_cert#6]
Traceback (most recent call last):
  File "/app/cdncert.py", line 39, in <module>
    Core.update_domain()
  File "/app/core.py", line 158, in update_domain
    db.update_domain(domain, user=user, cert_path=cert_path, private_key_path=private_key_path)
TypeError: Database.update_domain() missing 1 required positional argument: 'md5'

**Comment by 0xJacky** [comment]
已修复
